package com.test;

//Java program to calculate SHA-512 hash value 

import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 

public class SHAExample { 
	
	
	public static String encryptPassword(String input) 
	{ 
		try { 
			MessageDigest md = MessageDigest.getInstance("SHA-256"); 
			byte[] messageDigest = md.digest(input.getBytes()); 
			BigInteger no = new BigInteger(1, messageDigest); 
			String hashtext = no.toString(16); 
			while (hashtext.length() < 32) { 
				hashtext = "0" + hashtext; 
			} 
			return hashtext; 
		} 
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	} 

	public static void main(String args[]) throws NoSuchAlgorithmException 
	{ 
		System.out.println("HashCode Generated by SHA-512 for: "); 
		String s1 = "Welcome@1"; 
		String s2=  encryptPassword(s1);
		System.out.println(encryptPassword(s1)); 
		System.out.println(encryptPassword(s2)); 

		

	} 
} 
